// <auto-generated />
using System;
using IdeaCollectionSystem.Datalayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IdeaCollectionSystem.Datalayer.Migrations
{
    [DbContext(typeof(IdeaCollectionDbContext))]
    partial class IdeaCollectionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Idea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("EmailOutBoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdeaDocumentsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdeaReactionsIdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdeaReactionsUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmailOutBoxId");

                    b.HasIndex("IdeaDocumentsId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdeaReactionsUserId", "IdeaReactionsIdeaId");

                    b.ToTable("Ideas", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("EmailOutBoxId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EmailOutBoxId");

                    b.HasIndex("IdeaId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Departments", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.EmailOutBox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CommentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("EmailTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("IdeaId");

                    b.ToTable("EmailOutBoxes", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaDocuments", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FizeSize")
                        .HasColumnType("bigint");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadtedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaDocuments", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaReactions", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdeaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("UserId", "IdeaId");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaReactions", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcademicYear")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ClousureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FinalClousureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Submissions", (string)null);
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Avartar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("IdeaReactionsIdeaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdeaReactionsUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex("IdeaReactionsUserId", "IdeaReactionsIdeaId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Idea", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Category", "Category")
                        .WithMany("Ideas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Department", "Department")
                        .WithMany("Ideas")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.EmailOutBox", null)
                        .WithMany("Ideas")
                        .HasForeignKey("EmailOutBoxId");

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaDocuments", null)
                        .WithMany("Ideas")
                        .HasForeignKey("IdeaDocumentsId");

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Submission", "Submission")
                        .WithMany("Ideas")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.User", "User")
                        .WithMany("Ideas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaReactions", null)
                        .WithMany("Ideas")
                        .HasForeignKey("IdeaReactionsUserId", "IdeaReactionsIdeaId");

                    b.Navigation("Category");

                    b.Navigation("Department");

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Comment", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.EmailOutBox", null)
                        .WithMany("Comments")
                        .HasForeignKey("EmailOutBoxId");

                    b.HasOne("Idea", "Idea")
                        .WithMany("Comments")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Department", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.User", null)
                        .WithMany("Departments")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.EmailOutBox", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Comment", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Idea", "Idea")
                        .WithMany()
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaDocuments", b =>
                {
                    b.HasOne("Idea", "Idea")
                        .WithMany("IdeaDocuments")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaReactions", b =>
                {
                    b.HasOne("Idea", "Idea")
                        .WithMany("IdeaReactions")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Role", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.User", b =>
                {
                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaReactions", null)
                        .WithMany("Users")
                        .HasForeignKey("IdeaReactionsUserId", "IdeaReactionsIdeaId");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Idea", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("IdeaDocuments");

                    b.Navigation("IdeaReactions");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Category", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Department", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.EmailOutBox", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaDocuments", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.IdeaReactions", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.Submission", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("IdeaCollectionSystem.ApplicationCore.Entitites.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Departments");

                    b.Navigation("Ideas");

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
